Implement coord2address and category search
maengsanha/kakao-developers-api pull request #6
Opened 2022-01-12 05:59 UTC by GoRyne

2022-01-12 10:01 UTC, maengsanha requested changes

2022-01-12 10:01 UTC, maengsanha commented on v2/local/category_search.go
> +func CategorySearch(category_group_code string) *CategorySearchIterator {
It would be better to `PlaceSearchByCategory(groupcode string)`.

2022-01-12 10:01 UTC, maengsanha commented on v2/local/category_search.go
> +func (c *CategorySearchIterator) SetLongitude(x string) *CategorySearchIterator {
It would be better to `WithRadius(x, y float64, radius int)`.

2022-01-12 10:01 UTC, maengsanha commented on v2/local/category_search.go
> +func (c *CategorySearchIterator) SetRect(rect string) *CategorySearchIterator {
It would be better to `WithRect(rect int)`.

2022-01-12 10:01 UTC, maengsanha commented on v2/local/category_search.go
> +func (c *CategorySearchIterator) SortType(sort string) *CategorySearchIterator {
It would be better to `SortBy(typ string)`.

2022-01-12 10:01 UTC, maengsanha commented on v2/local/coord2address.go
> +func (b *CoordToAddressInitializer) RequestWGS84() *CoordToAddressInitializer {
Organize `Request...` to `Input(coord string)`.

2022-01-13 17:29 UTC, GoRyne commented
Resolve all conversations

2022-01-14 09:29 UTC, maengsanha approved these changes

2022-01-14 09:29 UTC, merged